### ISSUE TITLE
Testing Grammar::Debugger Failure

### ISSUE THREAD

**Issue by pendulm** [jnthn/grammar-debugger#22]
I am following [this](http://rakudo.org/how-to-get-rakudo/) instruction to install a Rakudo star perl6 enviroment, but I got this confusing error when I typed `panda install Task::Star`

> ==> Fetching Grammar::Debugger
> ==> Building Grammar::Debugger
> ==> Testing Grammar::Debugger
> ===SORRY!===
> Cannot call ACCEPTS(Regex: Mu); none of these signatures match:
>    (Regex:D $: Mu:U \a, *%_)
>    (Regex:U $: \topic, *%_)
>    (Regex:D \SELF: \topic, *%_)
>    (Regex:D \SELF: @a, *%_)
>    (Regex:D \SELF: %h, *%_)
> t/debugger.t .. 
> No subtests run 
> ===SORRY!===
> Cannot call ACCEPTS(Regex: Mu); none of these signatures match:
>    (Regex:D $: Mu:U \a, *%_)
>    (Regex:U $: \topic, *%_)
>    (Regex:D \SELF: \topic, *%_)
>    (Regex:D \SELF: @a, *%_)
>    (Regex:D \SELF: %h, *%_)
> t/tracer.t .... 
> No subtests run 
> ## Test Summary Report
> 
> t/debugger.t (Wstat: 0 Tests: 0 Failed: 0)
>  Parse errors: No plan found in TAP output
> t/tracer.t  (Wstat: 0 Tests: 0 Failed: 0)
>  Parse errors: No plan found in TAP output
> Files=2, Tests=0,  1 wallclock secs ( 0.01 usr  0.01 sys +  1.70 cusr  0.04 csys =  1.76 CPU)
> Result: FAIL
> test stage failed for Grammar::Debugger: Tests failed
>  in method throw at /home/mike/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm:1
>   in method install at /home/mike/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:142
>   in block  at /home/mike/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:214
>   in method resolve at /home/mike/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:208
>  in sub MAIN at /home/mike/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:18
>   in block <unit> at /home/mike/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:145

Failure Summary

Anyone have some ideas?

**Comment by edehont** [comment]
Same thing happens here, (Ubuntu 15.04 & Mint 17.2). I suppose a recent enhancement of Perl6 has consequences for some modules. Once that is straightened out, It will work again. I guess we just have to be a little patient. Much work is going on, just as we speak ;-)

By the way: This error happens while installing the modules. You can still play around with the core Perl6.

**Comment by jnthn** [comment]
Everything seems good on latest; resolving.
